server:
    port: 6666
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        connectionInitSqls: "SET NAMES utf8mb4"
        url: "jdbc:mysql://127.0.0.1:3306/OPEN_API_DB?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=GMT%2B8"
        username: root
        password: 123456
    redis:
        port: 6379
        database: 0
        host: 127.0.0.1
        mode: single
        password: 111111
        cluster:
            failed-attempts: 3
            master-connection-pool-size: 64
            nodes: 127.0.0.1:6379
            read-mode: SLAVE
            retry-attempts: 3
            retry-interval: 1500
            scan-interval: 1000
            slave-connection-pool-size: 64
        sentinel:
            fail-max: 3
            master: redis-cluster-seed
            nodes: 127.0.0.1:6379
            master-only-write: true
        single:
            address: 127.0.0.1:6379
        pool:
            conn-timeout: 5000
            max-active: 20
            max-idle: 20
            max-wait: 3000
            min-idle: 10
            size: 10
            so-timeout: 2000
            timeout: 3000
    main:
        allow-bean-definition-overriding: true